openapi: 3.1.0
info:
  title: Anony Plugin
  description: 文中に含まれる人名をイニシャル化して匿名にするプラグインです。
  version: 'v1'
servers:
  - url: http://localhost:3333
paths:
  /query:
    post:
      operationId: query
      summary: 文中に含まれる人名をイニシャル化して匿名にするときに使います。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Req'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Res'
components:
  schemas:
    Req:
      type: object
      properties:
        query:
          type: string
          description: Text to be initialed with a person's name
      required:
      - query
    Res:
      type: object
      properties:
        answer:
          type: string
          description: Sentences initialed with the person's name
      required:
        - answer